### ISSUE TITLE
Feature: track previous hnsince visits

### ISSUE THREAD

**Issue by hashbackup** [KristerV/HNSince#1]
First, I *love* hnsince!  I use Hacker News Daily to read the top 10 most discussed articles, but also wanted more than that, so I'd sometimes view Hacker News directly.  Seeing the same stuff over and over got really boring / annoying.  Hnsince fixes that, so thanks!

A couple of times I have clicked the wrong thing, hit the Back or Forward button, or something, and whereas I was viewing HN of the last 10 hours, it would change to 1 hour.

My feature suggestion would be to use a cookie to store a list of the last 5 visit times so that if this 1 hour thing happens, you can click on something to go forward or backward by time periods.   If the time period you are viewing is already in the list, don't change the list.  If it's not in the list, add it to the front and delete the 5th thing.  Might need the "currently viewing" time period too, dunno.

Thanks again for hnsince!

**Comment by KristerV** [comment]
oh wow, thanks. glad it's useful for someone besides myself. Where did you hear about it if I may ask?

This problem has happened to myself a few times too. How about listing the last 5 times at the bottom of the page as simple links? That way mobile isn't messed up and the UI is ultra basic (just like HN itself)?

**Comment by hashbackup** [comment]
I would put it at the top, only because when it happens, the page will already be positioned at the top and the links for previous times will be visible.  But bottom would be okay too.

You could just add the previous time period to the title line as a small link, like:
```
HN Since your last visit 1 hour ago                                                                 23 hours ago
```
Then if someone wanted to go back 3 time periods, which I think is kinda unusual, they could keep clicking the link on the right rather than trying to display 5 time periods somewhere.

**Comment by hashbackup** [comment]
Forgot to mention, I saw it on Hacker News!

**Comment by KristerV** [comment]
hmm, in that case I would instead just put it right below the title. Since it's only needed to be shown in case last visit is below 1h anyway. I'll get on this tomorrow (Paris time).

Hey! If you saw it on HN then you didn't upvote, because it didn't get any votes :D

**Comment by KristerV** [comment]
I tried many ways, but ended up with the 'list at the bottom' one. I have a goal to keep the UI familiar and clutter free. Adding info to the top that's not needed often just seems to work against it.

![image](https://user-images.githubusercontent.com/2750622/103173258-639a8d00-4862-11eb-8888-8168bf07c1e8.png)


Also, I hope I didn't mess up your session. At first I forgot to take the users existing session into account - basically a cardinal sin for this app.

How does this feel and does it fix your issue?

**Comment by hashbackup** [comment]
It looks good to me!

**Comment by KristerV** [comment]
Nice. Glad i could help!
