### ISSUE TITLE
Suggestion: previous visits list

### ISSUE THREAD

**Issue by hashbackup** [KristerV/HNSince#2]
Currently shows something like this:
```
Your previous visits

8 hours ago
23 hours ago
1 day ago
1 day ago
1 day ago
```
Suggest that if an interval is going to repeat (1 day in this case), use the next smaller interval (hours in this case) so that all previous visits are different. 

Or, another option would be to list them as 1 day, 2 hours
```
Your previous visits

8 hours ago
23 hours ago
1 day 2 hours ago
1 day 6 hours ago
1 day 10 hours ago
```

**Comment by hashbackup** [comment]
Another option would be to list only one previous visit, so in the above case it might show `8 hours earlier` first, then `15 hours earlier` next, then `3 hours earlier`, then `4 hrs earlier`, then `4 hrs earlier`.  I switched from `ago` to `earlier` because it seemed a little less confusing: the times become relative, so there is potential to get confused.  Maybe actually displaying a date & time would make it more obvious what's going on.

**Comment by KristerV** [comment]
the whole thing is handled by [Timex.diff()](https://hexdocs.pm/timex/Timex.html#diff/2). The 80/20 solution here would be to just filter duplicates (and keep the oldest entry).

This issue will stay open for a while, I'll probably continue work on this in february, after important life events pass :)

**Comment by KristerV** [comment]
I got some time so fixed this. @hashbackup better?

**Comment by hashbackup** [comment]
I went to HNSince this morning and it said "Since your last visit 22
hours ago", and 1d, 2d, 3d at the bottom.  Then I read some topics.
When I did reload, it said "Since your last visit 3 hours ago" at the
top, and 1d, 2d, 3d at the bottom.  It seems like "3 hours ago" should
have been the first thing listed at the bottom, but maybe I'm
confused.

**Comment by KristerV** [comment]
That is a bit confusing. I would assume the problem arises because time moves while you read. So 22h may have been 22:45 and after 1:30 of reading it's 1day and all the other ones also moved a day forward. I did look into this since I had the same confusion at one point.

I take it that this particular suggestion is fixed. If you have another feel free to open another issue.
