### ISSUE TITLE
Some topics have hnsince URL

### ISSUE THREAD

**Issue by hashbackup** [KristerV/HNSince#6]
Today I noted that some topics which are displayed "greyed out", and which I have never read, have a URL of http://hnsince.com instead of the real URL to the story.  The "n points by ..." line still has correct links to ycombinator.com

**Comment by hashbackup** [comment]
Just a sidenote: we talked before about some links being greyed out by mistake.  I realize now that the true problem is that the links are wrong and pointing to hnsince.com, and being greyed is a side-effect of that.

**Comment by KristerV** [comment]
oh man. so that's the problem. thanks for digging in! Fixed and deployed. Can you confirm?

**Comment by hashbackup** [comment]
Worked fine for me today.  Only 1 greyed-out link and I had actually
visited that topic before.

**Comment by KristerV** [comment]
great! Thanks for confirming.
