### ISSUE TITLE
UX Bug: Can't visit in a hurry, must commit an hour

### ISSUE THREAD

**Issue by hashbackup** [KristerV/HNSince#7]
I was thinking, what happens if I don't check HNSince for a few days.  Next time I'm going to get a huge list of topics that might take me a while to get through.  But if I only have 15 minutes, I'm kinda screwed.  

This got me thinking about another way HNSince might work.  Instead of tracking my last acces to hnsince.com, you could track my last click by making all links redirect through hnsince.com and setting a cookie to the latest timestamp of any topic viewed.  Basically a URL shortener that sets a timestamp cookie. This also avoids the database problem I think.  To handle the case of checking the last half of the page and not wanting to read any of these topics, a new link at the bottom like "Done" would set the cookie to the timestamp of the last topic.

So if I haven't been to hnsince for a few days, I'd get a long list of topics, click on the ones I want to read, and each time the timestamp cookie is updated.  If I only read a few articles, the next visit will show only topics created after my last topic read.  

There is a problem of reading through a list of topics I don't want to view and then stopping halfway, because I'll see those again my next visit.  But I don't think that's a huge deal.

**Comment by KristerV** [comment]
This is an interesting problem, I've also encountered this and left like 10 tabs open to not lose interesting stories.

Using the clicked link however makes everything so much more complicated usage wise. The stories are not ordered by date btw so you wouldn't really know which stories will disappear, which you'll see again. And I really don't want to have to click a "done" button on my every visit.

Alternative solution: how about I put a lock icon 🔓 after the last visit date. Clicking it will lock your last visit until you unlock it again. The only downside here is that if you let too much time pass stories may still disappear for newer ones with more points. But then again that's HNS core functionality so shouldn't be a problem.

What do you think about that?

**Comment by hashbackup** [comment]
Yeah, stories would have to be ordered by date, which to me, makes
sense for HNSince.

**Comment by KristerV** [comment]
I'm not sure I understand. HNS shows you the top posts since your last visit, so it makes sense to be ordered by points. If you just want to see the 10 top stories of the day then https://hckrnews.com/ is the service that does that. It _can_ be ordered by date, but then the UX would suffer once again. Also I generally don't want to read all stories, but the top 10 and if I have a lot of time I'll read more.

Do I understand correctly that the lock wouldn't help with your situation?

**Comment by hashbackup** [comment]
yeah, the lock would work too I think.

I thought HNS showed all stories since my last visit.  I don't really
care if they are ordered by points or by time.

**Comment by KristerV** [comment]
Well it's clear that the amount of stories shown is not clear (I may know why). I've opened a separate issue on that: #8.

As for reading something in a hurry: I've implemented the lock. Check it out and let me know how it feels @hashbackup.

(lol, I'm using it myself already)

**Comment by KristerV** [comment]
this was done a while ago and no answer, so closing.
